# Generated by Django 4.2 on 2024-12-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
