# Generated by Django 4.2 on 2024-12-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
