# Generated by Django 4.2 on 2024-12-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_height_alter_post_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
