# Generated by Django 4.2 on 2024-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
