# Generated by Django 4.2 on 2024-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_height_alter_post_image_alter_post_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='era_hidden',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_period_backend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_period_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
