# Generated by Django 4.2 on 2024-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_era_display_alter_post_time_period_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_period_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
