# Generated by Django 4.2 on 2024-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_post_time_period_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='era',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
