# Generated by Django 4.2 on 2024-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_remove_tag_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='wikidata_id',
            field=models.CharField(default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
