# Generated by Django 4.2 on 2024-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_tag_wikidata_id_alter_post_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='wikidata_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
