# Generated by Django 4.2 on 2024-12-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_tag_wikidata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
