# Generated by Django 4.2 on 2024-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_post_era_alter_post_colors_alter_post_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='materials',
            field=models.JSONField(default=list),
        ),
    ]
