# Generated by Django 4.2 on 2024-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_post_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
