# Generated by Django 4.2 on 2024-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_alter_post_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
