# Generated by Django 4.2 on 2024-12-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_post_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
