# Generated by Django 4.2 on 2024-12-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_comment_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
