# Generated by Django 4.2 on 2024-12-20 15:15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_post_winner_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_link',
            field=models.URLField(blank=True, help_text='Required for answers. Must be a valid URL', null=True),
        ),
    ] 