version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: 929696
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static_volume:
  media_volume:
