# Generated by Django 4.2 on 2024-12-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=150)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
