# Generated by Django 5.1.2 on 2024-12-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
